version: '3.5'
services:

  db:
    container_name: spectral-db
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    container_name: spectral-web
    build: .
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - ${PORT:-5000}:5000
    depends_on:
      - db

volumes:
  mysql-data:
  bundle_cache:
